name: 'Veracode Static Analysis Pipeline Scan'
description: 'Upload files to Veracode Static Analysis pipeline scan.'
inputs:
  appid:  # id of app
    description: 'appid'
    required: false
  filepath:  # id of input filepath
    description: 'filepath'
    required: true
  vid:  # id of input
    description: 'vid'
    required: true
  vkey:  # id of input
    description: 'vkey'
    required: true
# outputs:
#   result: #results.json
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.appid }}
    - ${{ inputs.filepath }}
    - ${{ inputs.vid }}
    - ${{ inputs.vkey }}
